---
title: "Guava's results analysis"
author: "Ana Valladares"
date: "2025-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dependencies, results='hide', message=FALSE}
library(ggplot2)
library(metan)
library(dplyr)
library(readxl)
library(MASS)
library(ggpubr)
library(DT)
library(stringr)
library(metan)
```

## Análisis de resultados del programa HTP-guava 

Análisis estadísticos descritivos son realizados en este Markdown, con los resultados obtenidos con el programa HTP-guava.

```{r Input.data1, echo=FALSE}
res.df = read.csv("~/Desktop/Guava/HTP-guava/outputs/results_2022.csv")
# Corrections , additions 
res.df$color_endo.meso = as.factor(res.df$color_endo.meso )
res.df$variedad <- str_extract(res.df$id, "(?<=-)[A-Z]+(?=-)")
res.df$variedad <- as.factor(res.df$variedad)
```

```{r outliers, echo=FALSE}
vars <- c("area_cm2_fruto",'area_cm2_mesocarpo','width_cm_mesocarpo','area_cm2_endocarpo','width_cm_endocarpo','num_units_semillas' ,'area_cm2_semillas','ratio_percent_semillas','ratio_percent_endocarpo') 

for (i in vars){
 plot = ggplot(res.df) + aes(x=variedad, y =res.df[,i])  +
  geom_boxplot(outlier.color = "red") + labs(x= "Variedades", y = i)
print(plot)
}
```

## Plots
```{r plotting_Density, fig.show='hold', out.width = "40%", collapse= TRUE}
vars <- c("area_cm2_fruto",'area_cm2_mesocarpo','width_cm_mesocarpo','area_cm2_endocarpo','width_cm_endocarpo','num_units_semillas' ,'area_cm2_semillas','ratio_percent_semillas','ratio_percent_endocarpo') 

for (i in vars){
plot = ggplot(res.df, aes(x=res.df[,i],group = variedad)) +
  geom_histogram(aes(y=..density..), colour= "black", fill="white", bins = 30)+
  labs(y= "Density", x = i)+
  geom_density(alpha=.2,fill="#FF6666")+facet_wrap(res.df$variedad)
print(plot)
}
```

